In [1]:
print("Hello World")

Hello World


In [ ]:
myName = input("Enter your name: ")
age = input("Enter your age: ")
score = input("What's your score? ")

print("Welcome " +myName+ " you are " +age+ " years old and you scored " +score+ " in your test")


# Set object

In [7]:
cities = {'lagos', 'Ibadan', 'Abuja', 'kano', 'Ogbomoso'}
#Set is an unorder array, It cannot be index
cities

{'Abuja', 'Ibadan', 'Ogbomoso', 'kano', 'lagos'}

# Dictionary

In [8]:
StudentInfo = {"Name": "Ade", "School":"OAU", "Course":"Chemiacal Engineering"}
StudentInfo

{'Name': 'Ade', 'School': 'OAU', 'Course': 'Chemiacal Engineering'}

In [12]:
StudentInfo["Name"]

'Ade'

## IF/ELSE STATEMENT

In [16]:
courseFee = 'paid'
if courseFee == 'free':
    print('I will attend the meeting')
else:
    print("I will attend")

I will attend


In [19]:
age = eval(input("How old are you? "))
if age >= 18:
    print("Congrats, access granted")
else:
    print("Sorry!")

How old are you? 30
Congrats, access granted


# Python Function

In [25]:
def addition():
    val1 = 56
    val2 = 23
    print(val1 + val2)

In [26]:
addition()

79


# Numpy and panda

In [1]:
import numpy as np
import pandas as pd


In [3]:
print("numpy version", np.__version__)
print("pandas version", pd.__version__)

numpy version 1.20.3
pandas version 1.3.4


In [4]:
# pip install --upgrade numpy
np.array(20)

array(20)

In [5]:
# create an array of range of values
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
np.linspace(0, 1, 3)

array([0. , 0.5, 1. ])

In [11]:
np.random.random((3,3))

array([[0.82857077, 0.11966195, 0.75989577],
       [0.40871174, 0.65379531, 0.31795939],
       [0.76147068, 0.4184411 , 0.77150699]])

In [18]:
val = np.random.randint(0,10,5)
val

array([6, 3, 7, 4, 6])

In [19]:
al = np.random.RandomState(45)
al = al.randint(10, size=6)
al

array([3, 0, 5, 3, 4, 9])

In [20]:
np.random.seed(45) #generate random but same value