# DATA SCIENCE NIGERIA (DNS)  DAY 2

In [ ]:
# To install numpy library use
pip install numpy
# or using conda installer
conda install numpy
# To install a particular version of numpy use:
pip install numpy==1.14.1
# Also install pandas library 
pip install pandas

In [1]:
# import the required packages
import numpy as np
import pandas as pd

In [2]:
#   check for version of your packages

print("Numpy version: ",np.__version__)
print("Pandas version: ",pd.__version__)

# type "python.exe -m pip install --upgrade numpy" or "pip install --upgrade numpy" to upgrade to latest version

Numpy version:  1.22.3
Pandas version:  1.2.4


# Introduction to Numpy

In [3]:
#create array of range of values
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
# create an array of specified length uniformly spaced between specified minimum and maximum value
# e.g create an array of five values uniformly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
#create a 3x3 array of uniformly distributed between 0 and 1
np.random.random((3,3))

array([[0.74151825, 0.13005094, 0.81410253],
       [0.77607285, 0.90576292, 0.43589636],
       [0.58334144, 0.32083121, 0.69845999]])

In [34]:
#create an array five lengths of random integers in the interval of 0 and 10
val = np.random.randint(0,10,5)
val

array([2, 4, 6, 4, 5])

In [46]:
np.random.seed(0) #to make the random display same value always
x1 = np.random.randint(10, size=6)
x1

array([5, 0, 3, 3, 7, 9])

In [57]:
rng = np.random.RandomState(42)
x1 = rng.randint(10, size=6)
x1

array([6, 3, 7, 4, 6, 9])

In [62]:
# create np array manually
x1 = np.array([1, 3, 5, 6, 8])

In [61]:
x2 = np.random.randint(10, size=(3,4))
x2

array([[7, 5, 1, 2],
       [2, 8, 1, 5],
       [8, 4, 0, 2]])

# indenxing an np Array

In [63]:
# get the value at index of 3
x1[2]

5

In [64]:
# np array can be indexed with negative indexing
x1[-2]

6

In [65]:
# you can modify the value of an np array
x1[4] = 10
x1

array([ 1,  3,  5,  6, 10])

In [66]:
#get the value at index row=1 and column=2
x2[1,2]

1

In [67]:
#change the value that exit at index of row=0 and column=-2
x2[0,-2]=10
x2

array([[ 7,  5, 10,  2],
       [ 2,  8,  1,  5],
       [ 8,  4,  0,  2]])

# Reshaping of array

In [69]:
# generate an array of lenght 12
ar =np.arange(1,13)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [70]:
## reshape array ar to 3x4 matrix
ar = ar.reshape(3, 4)
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
#using newaxis for row and column
ax = np.array([1,2,3,4,5,6])
ax.ndim

1

In [76]:
# reshape horizontally by placing np.newaxis along the row
ax[np.newaxis,:].ndim

2

In [78]:
# reshape vertically by placing np.newaxis along the column
ax[:,np.newaxis].shape

(6, 1)

# Introduction to Pandas

Pandas has two objects: pd.Series object and pd.DataFrame object #pd.Series is an array-like object that works as equivalent to numpy. #pd.DataFrame is a structured data object. It works in a table format with a row and column

In [39]:
# create series array
record = pd.Series([1, 2, 3, 4, 5, 6, 7, 8])
record

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [ ]:
# to see only the values of the series
record.values

In [40]:
# to see only the index of the series
record.index

RangeIndex(start=0, stop=8, step=1)

In [41]:
# from a specialized dictionary
states = {'Oyo':2500000, 'Lagos':6400000, 'Kano':4600000, 'Kaduna':3600000, 'Enugu':3400000, 'Imo':2300000}
statesdata = pd.Series(states)
statesdata

Oyo       2500000
Lagos     6400000
Kano      4600000
Kaduna    3600000
Enugu     3400000
Imo       2300000
dtype: int64

In [42]:
# creating dataframe from single dictionary
census = pd.DataFrame({'Population':statesdata})
census

Population
Oyo        2500000
Lagos      6400000
Kano       4600000
Kaduna     3600000
Enugu      3400000
Imo        2300000

In [43]:
# creating dataframe with some missing values
revenue = pd.Series({'Rivers':5000, 'Lagos':2000, 'Edo':7000, 'Kaduna':3000, 'Benue':4000, 'Imo':1500})
census = pd.DataFrame({'Population':statesdata, 'Revenue':revenue})
census

Population  Revenue
Benue          NaN   4000.0
Edo            NaN   7000.0
Enugu    3400000.0      NaN
Imo      2300000.0   1500.0
Kaduna   3600000.0   3000.0
Kano     4600000.0      NaN
Lagos    6400000.0   2000.0
Oyo      2500000.0      NaN
Rivers         NaN   5000.0

In [45]:
# list out the index 
census.index

Index(['Benue', 'Edo', 'Enugu', 'Imo', 'Kaduna', 'Kano', 'Lagos', 'Oyo',
       'Rivers'],
      dtype='object')

In [47]:
# list out the columns on the table
census.columns

Index(['Population', 'Revenue'], dtype='object')

In [48]:
# list out all the values of the dataframe
census.values

array([[    nan, 4.0e+03],
       [    nan, 7.0e+03],
       [3.4e+06,     nan],
       [2.3e+06, 1.5e+03],
       [3.6e+06, 3.0e+03],
       [4.6e+06,     nan],
       [6.4e+06, 2.0e+03],
       [2.5e+06,     nan],
       [    nan, 5.0e+03]])

# Exploratory Data Analysis

● Helps identify errors in data sets. 

● Gives a better understanding of the data set.

● Helps detect outliers or anomalous events.

● Helps understand data set variables and the relationship among them

# The Data Cleaning Process 
● Remove irrelevant data

● Deduplicate your data

● Fix structural errors

● Deal with missing data

● Filter out data outliers

● Validate your data

# Example: Working with US State Data

In [8]:
import pandas as pd

In [14]:
us_pop = pd.read_csv("C:\\Users\\Peter\\Downloads\\Data Analysis\\Practicals\\us_state_population.csv") 
us_area = pd.read_csv("C:\\Users\\Peter\\Downloads\\Data Analysis\\Practicals\\us_state_area.csv") 
us_abbrevs = pd.read_csv("C:\\Users\\Peter\\Downloads\\Data Analysis\\Practicals\\us_states_abbriev.csv")

In [15]:
us_pop.head()

state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

In [53]:
us_area.head()

state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

In [54]:
us_abbrevs.head()

state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

# Checking info of the data

In [55]:
# To have a general aggregation of the dataset, use describe() function
us_pop.describe()

year    population
count  2544.000000  2.524000e+03
mean   2001.500000  6.805558e+06
std       6.923547  2.855014e+07
min    1990.000000  1.013090e+05
25%    1995.750000  7.423805e+05
50%    2001.500000  1.597005e+06
75%    2007.250000  4.547104e+06
max    2013.000000  3.161288e+08

In [56]:
# To Helps understand data set variables and the relationship among them, use info() function
us_pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2544 entries, 0 to 2543
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   state/region  2544 non-null   object 
 1   ages          2544 non-null   object 
 2   year          2544 non-null   int64  
 3   population    2524 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 79.6+ KB


In [23]:
# let merge the abbreviation table and population table on the outer join
abb_pop = pd.merge(us_pop, us_abbrevs, how="outer", left_on="state/region", right_on="abbreviation")
abb_pop.head()

state/region     ages  year  population    state abbreviation
0           AL  under18  2012   1117489.0  Alabama           AL
1           AL    total  2012   4817528.0  Alabama           AL
2           AL  under18  2010   1130966.0  Alabama           AL
3           AL    total  2010   4785570.0  Alabama           AL
4           AL  under18  2011   1125763.0  Alabama           AL

In [24]:
# now we have two columns conveying the same information and we need to drop one
abb_pop = abb_pop.drop(labels=["abbreviation"], axis=1)
abb_pop.head()

state/region     ages  year  population    state
0           AL  under18  2012   1117489.0  Alabama
1           AL    total  2012   4817528.0  Alabama
2           AL  under18  2010   1130966.0  Alabama
3           AL    total  2010   4785570.0  Alabama
4           AL  under18  2011   1125763.0  Alabama

In [25]:
# let's double-caheck if there were any mismatches in the data using nulls:
abb_pop.isnull().any()

state/region    False
ages            False
year            False
population       True
state            True
dtype: bool

In [28]:
# let us see which of the datas are null
abb_pop[abb_pop["population"].isnull()].head()

state/region     ages  year  population state
2448           PR  under18  1990         NaN   NaN
2449           PR    total  1990         NaN   NaN
2450           PR    total  1991         NaN   NaN
2451           PR  under18  1991         NaN   NaN
2452           PR    total  1993         NaN   NaN

In [61]:
# let figure out which region has is mismatch data
abb_pop.loc[abb_pop["state"].isnull(), "state/region"].unique()

array(['PR', 'USA'], dtype=object)

In [62]:
# this shows that PR has no state and USA has no abbreviation so let's fix this error
abb_pop.loc[abb_pop["state/region"]=="PR", "state"]="Puerto Rico"
abb_pop.loc[abb_pop["state/region"]=="USA", "state"]="United States"

In [63]:
# lets check again if there is still any column with null value
abb_pop.isnull().any()

state/region    False
ages            False
year            False
population       True
state           False
dtype: bool

In [64]:
# now let us see the final table after error correction
abb_pop.tail()

state/region     ages  year   population          state
2539          USA    total  2010  309326295.0  United States
2540          USA  under18  2011   73902222.0  United States
2541          USA    total  2011  311582564.0  United States
2542          USA  under18  2012   73708179.0  United States
2543          USA    total  2012  313873685.0  United States

In [65]:
# now we can now merge the result with US area data using a similar columns
final_merge = pd.merge(abb_pop, us_area, on="state", how="left")
final_merge.head()

state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

In [66]:
# lets check if there are any mismatched data in the final_merge table
final_merge.isnull().any()

state/region     False
ages             False
year             False
population        True
state            False
area (sq. mi)     True
dtype: bool

In [67]:
# so lets  check for the region with null data
final_merge["state"][final_merge["area (sq. mi)"].isnull()].unique()

array(['United States'], dtype=object)

In [68]:
# let us drop the null values because the population density of the entire United State is 
# not relevant to our current discussion
final_merge.dropna(inplace=True)
final_merge.head()

state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

In [69]:
# lets check if there are any mismatched data in the final_merge table
final_merge.isnull().any()

state/region     False
ages             False
year             False
population       False
state            False
area (sq. mi)    False
dtype: bool

In [70]:
# Lets select the portion of the data corresponding with the year 2010 and the total population.
data2010 =final_merge.query("year == 2010 & ages == 'total'")
data2010.head()

state/region   ages  year  population       state  area (sq. mi)
3             AL  total  2010   4785570.0     Alabama        52423.0
91            AK  total  2010    713868.0      Alaska       656425.0
101           AZ  total  2010   6408790.0     Arizona       114006.0
189           AR  total  2010   2922280.0    Arkansas        53182.0
197           CA  total  2010  37333601.0  California       163707.0

In [71]:
# now lets compute the population density and display it in order. we will start by reindenxing
# our data on the state and then compute the result
data2010.set_index('state', inplace=True)
density = data2010['population']/data2010['area (sq. mi)']
density.sort_values(ascending=True, inplace=True)
density.head()

state
Alaska           1.087509
Wyoming          5.768079
Montana          6.736171
North Dakota     9.537565
South Dakota    10.583512
dtype: float64

In [72]:
density.tail()

state
Connecticut              645.600649
Rhode Island             681.339159
New Jersey              1009.253268
Puerto Rico             1058.665149
District of Columbia    8898.897059
dtype: float64

In [73]:
# Let us get the state with the highest landmax
final_merge['state'][final_merge['area (sq. mi)'].argmax()]
# state = us_area['state']
# landmax = us_area['area (sq. mi)']
# state[landmax.argmax()]

'Alaska'

# DATA SCIENCE NIGERIA (DNS) DAY 3

In [ ]:
import pandas as pd
read = pd.read_excel